-- Additional providers to approach 100 coverage
insert into public.providers (id, name, category, auth_type, required_secrets) values
('jira', 'Jira', 'project', 'apiKey', '{"JIRA_API_TOKEN"}'),
('asana', 'Asana', 'project', 'apiKey', '{"ASANA_ACCESS_TOKEN"}'),
('trello', 'Trello', 'project', 'apiKey', '{"TRELLO_KEY","TRELLO_TOKEN"}'),
('github', 'GitHub', 'code', 'apiKey', '{"GITHUB_TOKEN"}'),
('gitlab', 'GitLab', 'code', 'apiKey', '{"GITLAB_TOKEN"}'),
('bitbucket', 'Bitbucket', 'code', 'apiKey', '{"BITBUCKET_TOKEN"}'),
('linear', 'Linear', 'project', 'apiKey', '{"LINEAR_API_KEY"}'),
('clickup', 'ClickUp', 'project', 'apiKey', '{"CLICKUP_TOKEN"}'),
('zendesk', 'Zendesk', 'cs', 'apiKey', '{"ZENDESK_API_TOKEN"}'),
('freshdesk', 'Freshdesk', 'cs', 'apiKey', '{"FRESHDESK_API_KEY"}'),
('salesforce', 'Salesforce', 'crm', 'oauth', '{"SF_CLIENT_ID","SF_CLIENT_SECRET"}'),
('hubspot', 'HubSpot', 'crm', 'apiKey', '{"HUBSPOT_API_KEY"}'),
('pipedrive', 'Pipedrive', 'crm', 'apiKey', '{"PIPEDRIVE_API_TOKEN"}'),
('intercom', 'Intercom', 'cs', 'apiKey', '{"INTERCOM_ACCESS_TOKEN"}'),
('drift', 'Drift', 'cs', 'apiKey', '{"DRIFT_CLIENT_ID","DRIFT_CLIENT_SECRET"}'),
('segment', 'Segment', 'analytics', 'apiKey', '{"SEGMENT_WRITE_KEY"}'),
('amplitude', 'Amplitude', 'analytics', 'apiKey', '{"AMPLITUDE_API_KEY"}'),
('mixpanel', 'Mixpanel', 'analytics', 'apiKey', '{"MIXPANEL_TOKEN"}'),
('snowflake', 'Snowflake', 'db', 'apiKey', '{"SNOWFLAKE_USER","SNOWFLAKE_PASSWORD"}'),
('bigquery', 'BigQuery', 'db', 'apiKey', '{"GOOGLE_APPLICATION_CREDENTIALS"}'),
('postgres', 'Postgres', 'db', 'apiKey', '{"POSTGRES_URL"}'),
('mysql', 'MySQL', 'db', 'apiKey', '{"MYSQL_URL"}'),
('s3', 'Amazon S3', 'storage', 'apiKey', '{"AWS_ACCESS_KEY_ID","AWS_SECRET_ACCESS_KEY"}'),
('gcs', 'Google Cloud Storage', 'storage', 'apiKey', '{"GOOGLE_APPLICATION_CREDENTIALS"}'),
('azure-blob', 'Azure Blob Storage', 'storage', 'apiKey', '{"AZURE_STORAGE_CONNECTION_STRING"}'),
('calendar-google', 'Google Calendar', 'calendar', 'oauth', '{"GOOGLE_CLIENT_ID","GOOGLE_CLIENT_SECRET"}'),
('calendar-microsoft', 'Microsoft Calendar', 'calendar', 'oauth', '{"MS_CLIENT_ID","MS_CLIENT_SECRET"}'),
('notion', 'Notion', 'docs', 'apiKey', '{"NOTION_API_KEY"}'),
('confluence', 'Confluence', 'docs', 'apiKey', '{"ATLASSIAN_API_TOKEN"}'),
('elasticsearch', 'Elasticsearch', 'search', 'apiKey', '{"ELASTIC_URL","ELASTIC_API_KEY"}'),
('typesense', 'Typesense', 'search', 'apiKey', '{"TYPESENSE_API_KEY"}'),
('pinecone', 'Pinecone', 'vector', 'apiKey', '{"PINECONE_API_KEY"}'),
('weaviate', 'Weaviate', 'vector', 'apiKey', '{"WEAVIATE_API_KEY"}'),
('qdrant', 'Qdrant', 'vector', 'apiKey', '{"QDRANT_API_KEY"}'),
('mailchimp', 'Mailchimp', 'email', 'apiKey', '{"MAILCHIMP_API_KEY"}'),
('postmark', 'Postmark', 'email', 'apiKey', '{"POSTMARK_API_KEY"}'),
('resend', 'Resend', 'email', 'apiKey', '{"RESEND_API_KEY"}'),
('twilio', 'Twilio', 'sms', 'apiKey', '{"TWILIO_ACCOUNT_SID","TWILIO_AUTH_TOKEN"}'),
('sendgrid', 'SendGrid', 'email', 'apiKey', '{"SENDGRID_API_KEY"}'),
('claude', 'Anthropic Claude', 'llm', 'apiKey', '{"ANTHROPIC_API_KEY"}'),
('openai', 'OpenAI', 'llm', 'apiKey', '{"OPENAI_API_KEY"}'),
('mistral', 'Mistral', 'llm', 'apiKey', '{"MISTRAL_API_KEY"}'),
('gemini', 'Google Gemini', 'llm', 'apiKey', '{"GEMINI_API_KEY"}'),
('deepseek', 'DeepSeek', 'llm', 'apiKey', '{"DEEPSEEK_API_KEY"}'),
('cohere', 'Cohere', 'llm', 'apiKey', '{"COHERE_API_KEY"}'),
('perplexity', 'Perplexity', 'search', 'apiKey', '{"PERPLEXITY_API_KEY"}'),
('serpapi', 'SerpAPI', 'search', 'apiKey', '{"SERPAPI_API_KEY"}'),
('apify', 'Apify', 'docs', 'apiKey', '{"APIFY_TOKEN"}'),
('scrapingbee', 'ScrapingBee', 'http', 'apiKey', '{"SCRAPINGBEE_API_KEY"}'),
('openweather', 'OpenWeather', 'weather', 'apiKey', '{"OPENWEATHER_API_KEY"}')
on conflict (id) do nothing;


